storage:
  endpoint: ${STORAGE_ENDPOINT}
  accessKey: ${STORAGE_ACCESS_KEY}
  secretKey: ${STORAGE_SECRET_KEY}
  region: ${STORAGE_REGION}
  bucket: ${STORAGE_BUCKET}

recognize:
  token: ${RECOGNIZE_API_TOKEN}